### ISSUE TITLE
Send message to discord user

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/discord-bot#68]
# Context

We should like to send the discord user a message notifying them once the analysis on their guild has been completed.

# Solution

- [x] Consume the event `Event.DISCORD_BOT.SEND_MESSAGE`
- [x] Validate the data: `{ guildId: Snowflake, discordId: Snowflake, message: string, useFallback: bool }`.
- [x] Try to send the `message` as a direct message to `discordId`
- [x] If the direct message fails, and `useFallback: true`, then send it as a private message (in the guild).

## Documentation
- https://www.notion.so/Product-Roadmap-531f72f0dc6e43f697ba60e02fbf3fd3?p=c5045e8f31404e7b8d8eb75a6ca94dc6&pm=s
- https://github.com/RnDAO/tc-messageBroker/issues/36
- https://github.com/RnDAO/tc-serverComm/issues/130

**Comment by scientiststwin** [comment]
for creating a private thread we need below information: 

- name 
- startMessage 
- invitable

In my opinion, the message needs to be assigned to the `startMessage` and the `invitable` option should be set to `false`. if I'm wrong please correct me!
Also, what should we set for the `name`?
